### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#145] opened 2019-09-27 11:27 UTC
The following functions are exported from Singular.jl but have no documentation. It would be great if people who wrote these could write some docstrings and import them into the manual (.md files).

@raulepure @ederc @hannes14 @wbhart (someone else will have to take care of the ones written by @sebasguts and @steenpass)

I myself am particularly interested to learn what Singular.R is.

```
│     Singular.jacobi :: Tuple{spoly}
│     Singular.R :: Union{Tuple{spoly{n_unknown{T}}}, Tuple{T}} where T<:AbstractAlgebra.RingElem
│     Singular.R :: Union{Tuple{MPoly{T}}, Tuple{T}} where T<:AbstractAlgebra.RingElem
│     Singular.permute_variables :: Tuple{spoly,Array{Int64,1},PolyRing}
│     Singular.substitute_variable :: Tuple{spoly,Int64,spoly}
│     Singular.isquotient_ring :: Tuple{PolyRing}
│     Singular.jet :: Tuple{spoly,Int64}
│     Singular.slimgb :: Tuple{sideal}
│     Singular.slimgb :: Tuple{smodule}
│     AbstractAlgebra.Generic.derivative :: Tuple{spoly,Int64}
│     AbstractAlgebra.Generic.derivative :: Tuple{spoly,spoly}
```

**Comment by tthsqe12** [comment] 2021-11-11 16:46
duplicate of https://github.com/oscar-system/Singular.jl/issues/317

**Closed by tthsqe12** 2021-11-11 16:46 UTC
