### ISSUE TITLE
iszero fails for certain rings

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Singular.jl#557] opened 2022-02-15 15:13 UTC
Try running the following code in Oscar:
```julia
R, _ = quo(ZZ, 3*5)
S, (x,y) = Singular.PolynomialRing(R, ["x", "y"])
iszero(S(3)*S(5))
```
It returns `false`. Interestingly, the following works:
```julia
R, _ = quo(ZZ, 3*5)
P, (u, v) = R["u", "v"]
T = Oscar.singular_ring(P)
iszero(T(3)*T(5))
```
Why is this different? 

Follow up curiosity: For which one of the two implementations can I expect working Groebner-basis functionality?

**Comment by thofma** [comment] 2022-02-15 23:28
I have moved the issue to Singular.jl, as the problem seems to originate here.

**Comment by tthsqe12** [comment] 2022-03-04 11:53
Many bad things could be happening here. Let's start with this one.
```julia
julia> using Singular

julia> R = ResidueRing(Singular.Nemo.ZZ, 15)
Integers modulo 15

julia> S, (x, y) = Singular.PolynomialRing(R, ["x", "y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_RingElem{Singular.RingElemWrapper{Nemo.NmodRing, Nemo.nmod}}}[x, y])

julia> x*base_ring(x)(2)      # oops 2*x
x
```

@hannes14 do you see anything wrong in the relevant singular.jl code?
https://github.com/oscar-system/Singular.jl/blob/9d8d2fb5aa366c6c61baf78a913da9c554275241/src/poly/poly.jl#L642-L650

**Comment by tthsqe12** [comment] 2022-11-04 16:13
This is still an issue. In the last example, we have
```
julia> x*base_ring(x)(2)      # oops 2*x
x

julia> base_ring(x)(2)
2
```

Changing to `R = ResidueRing(Singular.ZZ, 15)`, I get the expected `2*x` for `x*base_ring(x)(2)`.

**Comment by tthsqe12** [comment] 2022-11-10 11:23
@hannes14 The `x*2` becoming `x` was indeed a singular.jl problem. However, Hechti's original problem probably stems from this line
https://github.com/Singular/Singular/blob/spielwiese/libpolys/polys/templates/p_Mult_nn__T.cc#L29
In the final example below, `p` stores a zero coefficient, and all predicates are wrong.

```
julia> R = ResidueRing(Singular.Nemo.ZZ, 15)
Integers modulo 15

julia> S, (x, y) = Singular.PolynomialRing(R, ["x", "y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_RingElem{Singular.RingElemWrapper{Nemo.NmodRing, Nemo.nmod}}}[x, y])

julia> p = x*2         # now correct
p_Mult_nn called
r->p_Procs->p_Mult_nn: 0x7f0a09b5ea80
p_Mult_nn__T called!!!
using ifndef HAVE_ZERODIVISORS branch
n_InpMult
julia aa: 1
julia bb: 2
julia cc: 2
2*x

julia> p = (x*3)*5      # problem in singular kernel
p_Mult_nn called
r->p_Procs->p_Mult_nn: 0x7f0a09b5ea80
p_Mult_nn__T called!!!
using ifndef HAVE_ZERODIVISORS branch
n_InpMult
julia aa: 1
julia bb: 3
julia cc: 3
p_Mult_nn called
r->p_Procs->p_Mult_nn: 0x7f0a09b5ea80
p_Mult_nn__T called!!!
using ifndef HAVE_ZERODIVISORS branch
n_InpMult
julia aa: 3
julia bb: 5
julia cc: 0
0

julia> (p, is_zero(p), length(p), leading_coefficient(p))
(0, false, 1, 0)
```

**Comment by hannes14** [comment] 2022-11-10 14:11
In https://github.com/oscar-system/Singular.jl/blob/master/src/libsingular/nemo/Rings.jl#L217
we have to check if p is a prime and set is_domain to 1 (if it is) or 0 (otherwise).

**Comment by tthsqe12** [comment] 2022-11-11 17:10
So here is the situation now on zero divisors.
I can essentially set 
```
    ring_struct.is_domain = is_domain_type(elem_type(R))
```
and the value currently used in Singular.jl is an unconditional `1`. The problem is now that
1. we have test code in Singular.jl where `is_domain_type(elem_type(R))` returns false. `R` is always happens to be free from zero divisors, but this cannot be infered from its type.
2. therefore, with this change, new code paths get exercised in the singular kernel.
3. Singular has many bad assumptions when `ring_struct.is_domain = 0`. For example, https://github.com/Singular/Singular/blob/4969bd84679f00e0090770de53eae064004f1330/kernel/GBEngine/kutil.cc#L4334 where a nullptr gets passed to julia.

**Comment by hannes14** [comment] 2022-11-12 17:40
At least (3: passing nullptr) should be fixed with https://github.com/Singular/Singular/commit/8e87445f9497ec7e004989fab73d4a66a3cdaf80

**Comment by tthsqe12** [comment] 2022-11-14 10:51
Certainly this code
```
  if (n_DivBy(zero, pGetCoeff(h), currRing->cf))
  {
    gcd = n_Ann(pGetCoeff(h),currRing->cf);
    go = true;
  }
```
will work now in nemo, but I'm not sure how useful it can be. zero is always divisible by anything.
```
julia> using Nemo

julia> R = ResidueRing(ZZ, 12)
Integers modulo 12

julia> divides(R(0), R(3))
(true, 0)

julia> divides(R(0), R(5))
(true, 0)

julia> divides(R(0), R(0))
(true, 0)
```

**Comment by fieker** [comment] 2022-11-14 11:05
On Mon, Nov 14, 2022 at 02:51:29AM -0800, dan wrote:
> Certainly this code
> ```
>   if (n_DivBy(zero, pGetCoeff(h), currRing->cf))
>   {
>     gcd = n_Ann(pGetCoeff(h),currRing->cf);
>     go = true;
>   }
> ```
> will work now in nemo, but I'm not sure how useful it can be. zero is always divisible by anything.
> ```
> julia> using Nemo
> 
> julia> R = ResidueRing(ZZ, 12)
> Integers modulo 12
> 
> julia> divides(R(0), R(3))
> (true, 0)
> 
> julia> divides(R(0), R(5))
> (true, 0)
> 
> julia> divides(R(0), R(0))
> (true, 0)
> ```
Can be please not allow the last one? 0/0? really?

**Comment by hannes14** [comment] 2022-11-14 11:33
Singular uses the test "if (n_DivBy(zero, pGetCoeff(h), currRing->cf))" to check if pGetCoeff(h) is a zero divisor.
Will improve the description.

**Comment by tthsqe12** [comment] 2022-12-06 13:43
fixed in https://github.com/oscar-system/Singular.jl/pull/613/files

**Closed by tthsqe12** 2022-12-06 13:43 UTC
Labels: bug
