### ISSUE TITLE
Coercion from BigInt to spoly{n_Zn} broken

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#326] opened 2020-12-26 10:15 UTC
Coercion produces garbage:
```julia
julia> R,(x1,x2,x3) = PolynomialRing(ResidueRing(ZZ, BigInt(2)^100),[ "x1", "x2", "x3" ]);

julia> R(BigInt(2)^98)
0
```

It works if one uses only the residue ring:
```julia
julia> S = ResidueRing(ZZ, BigInt(2)^100)
Residue ring of Integer Ring modulo 1267650600228229401496703205376

julia> S(BigInt(2)^98)
316912650057057350374175801344
```
The problem must be in the following function https://github.com/oscar-system/Singular.jl/blob/b64e3f1b5f8f8b8d5d89bad4d6fc61d4dd4b01c6/src/poly/PolyTypes.jl#L133-L140

**Comment by fingolfin** [comment] 2021-01-08 23:25
Turns out this is caused by a bug in Singular which @hannes14 fixed in https://github.com/Singular/Singular/commit/7234fd1a537971f2cbb4cd784dd3021e3d533776. I will look into updating Singular_jll...

**Comment by fingolfin** [comment] 2021-01-14 09:13
Actually now that I have had a chance to update Singular_jll to include that fix, it turns out that that this wasn't really the issue. There is something else going on.

(As a side note, while looking into this I discovered that there is an appalling amount of allocations being done for every use of CxxWrap... there are invocations that really should boil down to a simple `ccall` into Singular, which end up making 36 allocations)

**Comment by fingolfin** [comment] 2021-01-23 02:08
The code in question is now https://github.com/oscar-system/Singular.jl/blob/aeac8f346e4e95cc4ea71d2d921f238d212fa004/src/poly/PolyTypes.jl#L119-L123

Unfortunately the issue here persists, even with the latest Singular_jll which is based on https://github.com/Singular/Singular/commit/bad89c24b3352b9c5651915636ed5f2d7766baf9

```
julia> R,(x1,x2,x3) = PolynomialRing(ResidueRing(ZZ, BigInt(2)^100),[ "x1", "x2", "x3" ]);

julia> R
Singular Polynomial Ring (Coeffs(17)),(x1,x2,x3),(dp(3),C)

julia> R(BigInt(2)^98)
0

julia> S = base_ring(R)
Singular coefficient ring over Residue ring of Integer Ring modulo 1267650600228229401496703205376

julia> S(BigInt(2)^98)
316912650057057350374175801344
```

It is clearly related to the size of the bigint: the issue crops up as soon as it takes up more than one limb:
```
julia> R(big(2)^62)
4611686018427387904

julia> R(big(2)^63)
0
```
It does work if one initializes with an `n_Z` or `fmpz`, as those go through different code paths; so it'd be trivial to work around this, by replacing the quoted method above (heck, just deleting it solves the issue, as we'll fall back to a generic function which is perhaps slightly less efficient, but at least produces a correct result).

@hannes14 perhaps you have any ideas?

**Comment by tthsqe12** [comment] 2021-08-11 08:42
Seems to be fixed now. Can't say when though.

**Closed by tthsqe12** 2021-08-11 08:42 UTC
