### ISSUE TITLE
`lift_std` gives wrong results

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#491] opened 2021-09-06 09:48 UTC
```julia
julia> Singular.PolynomialRing(Singular.QQ, ["x"])
(Singular Polynomial Ring (QQ),(x),(dp(1),C), Singular.spoly{Singular.n_Q}[x])

julia> I = Singular.Ideal(Fx, zero(Fx))
Singular Ideal over Singular Polynomial Ring (QQ),(x),(dp(1),C) with generators (0)

julia> Singular.lift_std(I)
(Singular Ideal over Singular Polynomial Ring (QQ),(x),(dp(1),C) with generators (0), [])

julia> J, M = Singular.lift_std(I)
(Singular Ideal over Singular Polynomial Ring (QQ),(x),(dp(1),C) with generators (0), [])

julia> gens(J)
1-element Vector{Singular.spoly{Singular.n_Q}}:
 0

julia> M
[]
```

The matrix `M` does not work with the generators of `J`. Either `J` should have zero generators or the matrix should be a 0 x 0 matrix.

@tthsqe12 @hannes14

**Comment by YueRen** [comment] 2021-09-06 09:55
I think this can be fixed by changing `mpNew(1,0)` to `mpNew(1,1)` in kernel/ideals.cc line 916 onwards:

```c  
  if (idIs0(h1))
  {
    *ma=mpNew(1,0);
    if (lift3)
    {
      *syz=idFreeModule(IDELEMS(h1));
    }
    return idInit(1,h1->rank);
  }
```

**Comment by tthsqe12** [comment] 2021-09-06 10:13
I thought lift_std is supposed to return a vector polynomials (basis) and a matrix (tranform). Why is it returning an ideal?

**Comment by hannes14** [comment] 2021-09-06 10:50
Comes from the question: how many generators has the zero ideal?
Will be fixed in Singular as Yue proposes:
https://github.com/Singular/Singular/commit/a6a6582eb185fcfc0c4eb4da20eeaf50d5ad70e5

**Comment by fieker** [comment] 2021-09-06 11:03
On Mon, Sep 06, 2021 at 03:50:50AM -0700, Hans Schoenemann wrote:
> Comes from the question: how many generators has the zero ideal?
not really... if the input is n generators, and the output has 1, then
the matrix needs to be 1 x n
The matrix needs to match the other arguments

**Comment by hannes14** [comment] 2021-09-06 11:07
@fieker: it was changed in that sense, see commit above

**Comment by tthsqe12** [comment] 2021-11-09 17:00
The `M` in the issue is now the 1x1 matrix `[0]`.

**Closed by tthsqe12** 2021-11-09 17:00 UTC
Labels: bug
